services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 1234:1234
    environment:
      PG_DSN: "host=db user=app password=app dbname=app sslmode=disable"
      JWT_SECRET_KEY: "change_me"
  nginx:
    build:
      context: .
      dockerfile: ./configs/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
      PG_DATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgres-data:
