{
 "title": "api dashboard v2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes,job)"
    }
   },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Go Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(go_sql_in_use_connections{job=\"$job\"})",
     "legendFormat": "inuse conn"
    },
    {
     "expr": "avg(go_sql_idle_connections{job=\"$job\"})",
     "legendFormat": "idle conn"
    },
    {
     "expr": "avg(go_sql_open_connections{job=\"$job\"})",
     "legendFormat": "open conn"
    },
    {
     "expr": "avg(rate(go_sql_wait_count_total{job=\"$job\"}[$interval]))",
     "legendFormat": "wait conn"
    },
    {
     "expr": "avg(rate(go_sql_wait_duration_seconds_total{job=\"$job\"}[$interval]))",
     "legendFormat": "wait time"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_alloc_bytes{job=\"$job\"})",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"$job\"}[$interval]))",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=\"$job\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"$job\"})",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "gRPC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"$job\"}[$interval])) by (grpc_service)",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (grpc_code)\n/ ignoring(grpc_code) group_left sum(rate(grpc_server_handled_total{job=\"$job\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.75, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "75%"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.25, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "25%"
    },
    {
     "expr": "histogram_quantile(0.10, \n  sum(rate(grpc_server_handling_seconds_bucket{job=\"$job\",grpc_type=\"unary\"}[$interval])) by (le)\n)",
     "legendFormat": "10%"
    }
   ]
  }
 ]
}